export default {
  login: 'devhims',
  id: 17825870,
  node_id: 'MDQ6VXNlcjE3ODI1ODcw',
  avatar_url: 'https://avatars.githubusercontent.com/u/17825870?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/devhims',
  html_url: 'https://github.com/devhims',
  followers_url: 'https://api.github.com/users/devhims/followers',
  following_url: 'https://api.github.com/users/devhims/following{/other_user}',
  gists_url: 'https://api.github.com/users/devhims/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/devhims/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/devhims/subscriptions',
  organizations_url: 'https://api.github.com/users/devhims/orgs',
  repos_url: 'https://api.github.com/users/devhims/repos',
  events_url: 'https://api.github.com/users/devhims/events{/privacy}',
  received_events_url: 'https://api.github.com/users/devhims/received_events',
  type: 'User',
  site_admin: false,
  name: 'Himanshu Gupta',
  company: 'Cosmoreal',
  blog: 'https://cosmoreal.io/',
  location: 'Bangalore, India',
  email: null,
  hireable: true,
  bio: 'Practicing dev, design, teaching, and living a meaningful life.',
  twitter_username: 'devhims',
  public_repos: 39,
  public_gists: 2,
  followers: 15,
  following: 7,
  created_at: '2016-03-14T10:22:32Z',
  updated_at: '2021-02-02T10:53:57Z',
};
